# This file is practically a copy/paste from the goreleaser docs.
# Goreleaser has created an action specifically for Github actions
# and you can see the full instructions here:
# https://goreleaser.com/ci/actions/?h=github+ac.
# I have made just a couple of modifications to this for my needs.
#
# First, I modified the on section at the top of the file which tells Github actions to
# activate this action when a tag is pushed to this project. Second,
# I modified the version value so it sets the version number to the tag I created.
# Finally, I changed the GITHUB_TOKEN environment variable value to
# ${{ secrets.PUBLISHER_TOKEN }}

name: goreleaser

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: ${{ env.GITHUB_REF_NAME }}
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLISHER_TOKEN }}
